---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY
    - secure: >-
        SIYKQXYk0Z1VfjaDBGMW0aAsF0lLDB8u7h02yOrhBe+AF5u6O4uWO7jhfn5MGSHWW7L
        KsywqRETDpfufwFbMUV1Jn4oSxp80k3ZQ7bPJ53aCVzXvlxyKLYAly+pWV7KxCe0anZ
        9R9BVTMI5VZgpQAz7ZM7+eGdHwQzeFaOxs2jKksQ3h4TbWNdi02r/YZGq86cdzy5RuG
        2dGEV0LdOACTO4wwYR5gOyk1oPrNSjZ/9HWB2dCOwQgvVS00VQckqaTwoeTIhcHLKnh
        eUOTtPqeNUG9JwE7Tevr8LdfXKqNCS3uvuyfA99enY07Xeig1DRY/43ZBH17lBmZSSW
        njSDlmM9XnKqU8XrUdHb+A/dA1BQvjaP10GbScbTcqbCifC2H1bWLaabVAIFvuxyrUb
        xlKg6MStHHn61cKP1Jk1tvYVbNfxd/3j/67lZS8V40kmpk3LhAMuPnrODi0ZqVWC+0W
        qqRl7SDLK1BijjyMUFtdKkwVTAYHsis70g/iYMrRN8LMD77TX+RMg2WsN3zlVfU1ck/
        pv76rPbNZW5TFXdvz8s9JZm6i4aj+u8LJhbwrnQe9E8A5XIkP6UKiTnpyY3HY1I/4b3
        3V52hNhX81yWRB3QPG/+osrCGXML8ShXRcVTdCjgBBvpLCyvxaZ7b2U16wjIS1OK5FV
        az4HnJ1iGqvoY=
    # AWS_SECRET_KEY
    - secure: >-
        mfrI/edHj0K7/5gb32BIDM7Rc23l0Yeu4ZrC+aJrV+PjmHjM3i5UeaL9+Fv5C4gjmuP
        04wVSELv+R8iFmdWEcb9nzQl7xhKbcEpkrNtthqKguXciEh5nKGGcWlwijyRJ4Q7zuq
        x0URmyeyT86W+K3IriSHGCWNMNewRCY0yWwwxmvf7SUp8jll9iqPB/pZrk0OCqTdOWm
        10BHL3YmYJv/4cohLwAu9XWfS5gW6HO3VhoG5RkHv+exXUXettntzRDB04g57qngrry
        wR+E2OQzNFhYjBgT8QG+wwncuybqM24agwf1jFvfffi+ElnK1YiZ/eG4vTAH0VIZLIo
        /fhGe/R2wC+NHCLJiOWA3mUgfcSVcUg3WTl5ar8F57SptEJe45sxvJdQwhJjTlwyUvx
        cTWThJQsZuApgL2DPc7fKYAc5nSh7cXOmiU9JmXo+glEEn6zFm4qbqEoHIJeDjIxF8K
        Tk/CBVefIkeYqSEjA12baPqBsbuuZ0mkVYCXFRelsWUE7IL18534NDOr0HQnegcEF11
        7FM97ZxSrN70rMerHRCd0I9xjYPdfxmTbD84jEfSwFRVZvVT0drBtt853ALxR3ytVDl
        hS7EcXyuUfA6X6fbjM7EllczFonGF6gQpi38sFBCgpAHFuhXe+lB55T1ChgTGnNyDN3
        RSfPAppJIXRhQ=
    - BUILD_REGION="us-east-2"
    - DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    # - IMAGE_VERSION=
    - PACKER_VERSION="1.4.1"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

before_install:
  # install packer.io
  - curl --output /tmp/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export IMAGE_VERSION=$(./bump_version.sh show)
  - eval $(./update_env.py)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create a production image
  - provider: script
    script: packer build --timestamp-ui src/packer.json
    on:
      tags: true
  # # create a testing image
  # - provider: script
  #   script: export IMAGE_VERSION=${IMAGE_VERSION}-pre &&
  #     packer build src/packer.json
  #   on:
  #     tags: false
