---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "H94AY1PnldXjqnN7dzuZGcRNwhSOfsl8+EyrKiyU8pxYw90hwms2toWO\
    ws04kUb9IF7EVat8LI52N/1DqhvlIPyzUEkPNSSY+0X2MX+zymwDvBj2FlojNLsF5kX\
    LQJ2A9YQGM6LE8GY6PpOLrLsbhLgSaTEHViVY9IRTWUREyHlD/si+7fNY1q+EPnbFId\
    qto7+S39Ab1YM3TpwEWlrZ5B4UIqL+5Nt2y+kCh0gLbhggauXAAyGUSbfFPsWG/NUUt\
    2hknErBWfX7/Hcuwz4mG6jRQZTX3yHUVpSkBu9lZ1P4ykZVV4bK83XmWayosZDFDckn\
    5UftOEUza3cG9dliIGBfpl211OvNDoze3Fm/lda9obIWlDVyRW26IsfYnFGAdtcbz/X\
    Tq9aKMr9AaDrAfWKq91j4CvLm0voPr6j9cBOwzJVOhTy3aTbFT7vFKncTyoSTrS6UR2\
    S+ymQ0sDnCY91s7w2hXn1K2vNJ3oIIqVUwkpPKCodUejiRmrSbxkbnqw8joIt7u8M+3\
    LT4UsFJrilpig9/T9JQCODy0VWFr/hNCPRZ+u3xWK0nDU+IeqG+e76u6VLQatIY9HS/\
    kdDLkyNEqR2icNpllAfGVOHIcpFuBphyj6rE5jBBng/QXvQSqki+gH2hNLtrD+JaYhI\
    6rWP311T+8MwHSWCA2hUjyg="
    - AWS_DEFAULT_REGION="us-east-2"
    # AWS_SECRET_ACCESS_KEY
    - secure: "xl4fJL6Xr9j13On7XDH8/v4Md26c5GDL0bZrVQHQbWt8BbfYP3IO2w69\
    /fjlkMYLuPwgWQot44zXY1akgjOq5aOTqwXybHX4CLz/xWYcZZVOCBp91Kf1bfxMo3Y\
    TJ8EWI5tbS9PdPw0GZjYQ1YYdnX5OV9+VyYMVsbFB8vvH/N/UYB0hxCm+aRZ+/8s3io\
    EGTvSLTqEsJuUmTOcQNH7oahtY+Zv7VdwVnXAQmaQKVXgfMxgxeMMnbk0rNcAXik3jb\
    vj775NA+qE8tCdPtPutYiJy6+xGbQI3kNIbgGBjgGM4SuWTXkis/KNRnpZHCB7bBCan\
    oHgU7Jyus2HBV7ECpIHKpZOFUfWdDUZt0SP8WHMaZxz3xVGqPr9KMTeQHDZ/amh0P8Z\
    B4GvH/XtJZmLa/Za+C7cLFiU/9HAcOS/DIHJ51dHz8+uGjGVcfAzUUvNqi9LpnjG5ld\
    u4urAC38+lh0KNd7CH35WDQjenZ1Ti6MFzQFDAyFXlcjbHroOl0MOCPb7CQ2LTv4GEL\
    4SlrMLA/vrasKkRzn8Y7YBTurCBychkonFe1bBfLkAikG/RrL6+oqmK6qJz7QF2DfgR\
    D06VRI+21wFa3Raikv6O4AEcd+MFjNpLdqrVortNj3V3ufHvHfxKgS8souPmfW1rLcF\
    Z9xhv7GQ6S00KGjI3u2JtkLU="
    - PACKER_BUILD_REGION="us-east-2"
    - PACKER_DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - PACKER_VERSION="1.4.2"
    - TERRAFORM_VERSION="0.12.3"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

before_install:
  # Install terraform
  - >
    wget
    https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
    -O /tmp/terraform.zip
  - sudo unzip -d /opt/terraform /tmp/terraform.zip
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  # install packer
  - curl --output /tmp/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export PACKER_IMAGE_VERSION=$(./bump_version.sh show)
  - eval $(./update_env.py)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create a production image
  - provider: script
    script: packer build --timestamp-ui src/packer.json
    on:
      tags: true
