---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "gehBfc/5OdhA5btSFzg+dFObDgnDGxnReHwe9yUZdy5JS0QQIVyXu8tz\
    MIsQ/vpGRHGLdcGujGg5+RULDKq92wvKTPaBXONkBtZkjAV1o0LaLygPx/9Wji/BmlE\
    Yc0NMqBy5VWJPhhHNBKxyTt1O0SsrGOP3nnZiDSJhOaEZYOR15QRWZbFvUU3Zpu8qt8\
    Bobx5FjB6+2hUuT8kEzR0zN9NjU3/i5v8KaB1yBEFQJQXIXb6bKDoNsqnrmNM0b8EEc\
    a985Mgtwu4Cp95sCnRy3h8UcHcd2WE29Y4d8CC/pewFaPI9kX+9bPpswARQPLniERzH\
    TB2YEwgmYyWibC5ipcv3ON46JIOHLaYL7uPhI718W1lhE9sIApUZQD5z9R/wYjUSE+a\
    6fBCs+9ieZV9w1Mr0AAIQDAm4u/JC5ASifVlurRd2vW75fg6UKefSa/DuGv1JfvXPst\
    kRcwSz5+pM7FYh7e5e/ThKJk0KmCz+MtGW0pozXxY6hqFBdx2LmZ49mARBr8mvmsML7\
    X+fCAAakMeMf/ntmZO2VEao8p6eZi1N40fZ1anzfTcljHRbDZOsgFwfeVap6KlVjfUE\
    4fLSNPzh2nGhCFxhxIr1FmIM9LD7TuXnTtrKF8o2OhyH9N5OiI/Mpb+ZuxN8jAQUOpG\
    HOEHSwBlW4TmwUXTnHkA9BYQ="
    - AWS_DEFAULT_REGION="us-east-2"
    # AWS_SECRET_ACCESS_KEY
    - secure: "xl4fJL6Xr9j13On7XDH8/v4Md26c5GDL0bZrVQHQbWt8BbfYP3IO2w69\
    /fjlkMYLuPwgWQot44zXY1akgjOq5aOTqwXybHX4CLz/xWYcZZVOCBp91Kf1bfxMo3Y\
    TJ8EWI5tbS9PdPw0GZjYQ1YYdnX5OV9+VyYMVsbFB8vvH/N/UYB0hxCm+aRZ+/8s3io\
    EGTvSLTqEsJuUmTOcQNH7oahtY+Zv7VdwVnXAQmaQKVXgfMxgxeMMnbk0rNcAXik3jb\
    vj775NA+qE8tCdPtPutYiJy6+xGbQI3kNIbgGBjgGM4SuWTXkis/KNRnpZHCB7bBCan\
    oHgU7Jyus2HBV7ECpIHKpZOFUfWdDUZt0SP8WHMaZxz3xVGqPr9KMTeQHDZ/amh0P8Z\
    B4GvH/XtJZmLa/Za+C7cLFiU/9HAcOS/DIHJ51dHz8+uGjGVcfAzUUvNqi9LpnjG5ld\
    u4urAC38+lh0KNd7CH35WDQjenZ1Ti6MFzQFDAyFXlcjbHroOl0MOCPb7CQ2LTv4GEL\
    4SlrMLA/vrasKkRzn8Y7YBTurCBychkonFe1bBfLkAikG/RrL6+oqmK6qJz7QF2DfgR\
    D06VRI+21wFa3Raikv6O4AEcd+MFjNpLdqrVortNj3V3ufHvHfxKgS8souPmfW1rLcF\
    Z9xhv7GQ6S00KGjI3u2JtkLU="
    - CURL_CACHE_DIR="$HOME/.cache/curl"
    # GITHUB_ACCESS_TOKEN
    - secure: "AIve2BptbZX6Nhcs9c9ACRfKxZJqqkK9q0X7ZhJaNv+QWbNEr1KP1azY\
    WcsROUV5FRyTprqhYdpSuM7CMwtVMwvMoCfm9EbIF5z+UrngkYD8lRr6Yf8OXLhAqz2\
    nleK01KgYmon6E8ryyd3K3kBSyzvW2kwePPsUUge+Qtas1HDKRmLZNGkqu/ISqTxgHj\
    HkMByfExVWjneKD76uObQu+gF+SfTBNmDpIqj1RiKTp2qgcU47z8vsUG/DaOMNLpUXG\
    MeTmad2GFgYUMru6NdrMFNSuaC808esVq+PpkIVA98Uw1XyCTXmeyulwJlHAe0Wc2c+\
    BgAE6K+PdQ3Zd7Y3JkDeijIzHHaVWr6/v3hPCrVCsZWeW0tce4Ae1tSRPgRiCon0Pbs\
    Fedexg9jLXHt8oF6ffCJBqwGBwQU8gfQEUyMmccgYU/2WVIL1+CbnwG7oMK6UZRThQJ\
    fYAz6hcPHPsODh0bv1NNx1ZELkG5SvBud26OF4XbldOaYzWmw4phIjEKj3y2EFT7TwB\
    0c9KeYGSEkUs2Xb3Lgme9rcMiL2sXYMxRW2KdP7+1xIjcuskOJi2P/6fHcA1cK++s3z\
    iDSDHYPKra3ebebVTl74MJr+dHrun4o8k+stvKgsEqxGVYJXYG5R1PCtWPw51JTs9Vy\
    XFeSaVYPYu1lvBX6Sd8IJX1o="
    - PACKER_BUILD_REGION="us-east-2"
    - PACKER_DEPLOY_REGION_KMS_MAP="us-east-1:alias/cool/ebs,
                                    us-east-2:alias/cool/ebs,
                                    us-west-1:alias/cool/ebs,
                                    us-west-2:alias/cool/ebs"
    - PACKER_VERSION="1.4.3"
    - PACKER_ZIP="packer_${PACKER_VERSION}_linux_amd64.zip"
    - TERRAFORM_VERSION="0.12.7"
    - TERRAFORM_ZIP="terraform_${TERRAFORM_VERSION}_linux_amd64.zip"


# Cache pip packages, pre-commit plugins, and some curl downloads to
# speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $CURL_CACHE_DIR

before_install:
  # Make a cache directory for curl downloads
  - mkdir -p $CURL_CACHE_DIR
  # Install terraform
  - curl --output "${CURL_CACHE_DIR}/${TERRAFORM_ZIP}"
      --time-cond "${CURL_CACHE_DIR}/${TERRAFORM_ZIP}" --location
      "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TERRAFORM_ZIP}"
  - sudo unzip -d /opt/terraform "${CURL_CACHE_DIR}/${TERRAFORM_ZIP}"
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  # Install packer
  - curl --output "${CURL_CACHE_DIR}/${PACKER_ZIP}"
      --time-cond "${CURL_CACHE_DIR}/${PACKER_ZIP}" --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/${PACKER_ZIP}"
  - sudo unzip -o -d /usr/local/bin "${CURL_CACHE_DIR}/${PACKER_ZIP}"

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export PACKER_IMAGE_VERSION=$(./bump_version.sh show)
  # Install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - pre-commit run --all-files
  - ./patch_packer_config.py query-github src/packer.json
  - packer validate src/packer.json
  - pytest

before_deploy:
  - pip install travis-wait-improved

deploy:
  # create an image when tagged
  - provider: script
    # preserve patch to packer configuration by skipping cleanup
    skip_cleanup: true
    script: travis-wait-improved --timeout=30m packer build --timestamp-ui
      src/packer.json
    on:
      tags: true
