---
version: '3.7'

services:
  gophish:
    volumes:
      - gophish-home:/home/cisa

  postfix:
    ports:
      - target: "25"
        published: "25"
        protocol: tcp
        mode: host
      - target: "587"
        published: "587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "993"
        protocol: tcp
        mode: host
    volumes:
      - postfix-etc:/etc
      - postfix-home:/home
      - postfix-root:/root
      - postfix-var:/var

volumes:
  gophish-home:
  postfix-etc:
  postfix-home:
  postfix-root:
  postfix-var:
