---
version: '3.7'

services:
  gophish:
    volumes:
      - "/var/pca/pca-gophish-composition/data:/home/cisa/data"

  postfix:
    ports:
      - target: "25"
        published: "25"
        protocol: tcp
        mode: host
      - target: "587"
        published: "587"
        protocol: tcp
        mode: host
      - target: "993"
        published: "993"
        protocol: tcp
        mode: host
    volumes:
      - postfix-etc:/etc
      - postfix-root:/root

volumes:
  postfix-etc:
  postfix-root:
