---
- hosts: all
  name: Various extras to configure the environment to the PCA team's liking
  become: yes
  become_method: sudo
  tasks:
    - name: Install extra software used by the PCA team
      ansible.builtin.package:
        name:
          - bluefish
          - firefox-esr
    # Add VNC user to docker group so that PCA operators can
    # successfully execute docker-compose commands.
    - name: Add VNC user to docker group
      ansible.builtin.user:
        append: yes
        groups:
          - docker
        name: "{{ lookup('aws_ssm', '/vnc/username') }}"
