---
- hosts: all
  name: Various extras to configure the environment for operators
  become: yes
  become_method: sudo
  tasks:
    - name: Install extra software used by operators
      ansible.builtin.package:
        name:
          - bluefish
          - dnsutils
          - firefox-esr
          - thunderbird
