---
- hosts: all
  name: Install extra software used by PCA team
  become: yes
  become_method: sudo
  tasks:
    - name: Install utilities used by gophish-tools helper scripts
      package:
        - at
        - jq
    - name: Install bluefish text editor
      package:
        name: bluefish
    - name: Install Firefox web browser
      package:
        name: firefox-esr
