---
- hosts: all
  name: Install extra software used by PCA team
  become: yes
  become_method: sudo
  tasks:
    - name: Install utilities used by PCA helper scripts
      package:
        name:
          - at
          - jq
    - name: Install bluefish text editor
      package:
        name: bluefish
    - name: Install Firefox web browser
      package:
        name: firefox-esr
