---
- hosts: all
  name: Install and configure PCA GoPhish Docker composition
  become: yes
  become_method: sudo
  roles:
    - pca_gophish_composition
  tasks:
    - name: Configure PCA GoPhish Docker composition
      block:
        - name: >
            Create a gophish group with the same GID as inside
            gophish-docker
          ansible.builtin.group:
            name: gophish
            gid: 421
            system: yes
        - name: Create mount point for GoPhish persistent data volume
          ansible.builtin.file:
            mode: 0755
            path: "{{ pca_gophish_composition_path }}/data"
            state: directory
        - name: Change GoPhish published port from 3380 to 80
          ansible.builtin.lineinfile:
            path: "{{ pca_gophish_composition_path }}/docker-compose.yml"
            regexp: "published: 3380$"
            line: "        published: 80"
            state: present
        - name: >
            Copy docker-compose.production.yml to pca-gophish-composition
            dir
          ansible.builtin.copy:
            mode: 0644
            src: docker-compose.production.yml
            dest: >
              {{ pca_gophish_composition_path }}/docker-compose.production.yml
        - name: Set up pca-gophish-composition systemd service
          block:
            - name: Install systemd service file for pca-gophish-composition
              ansible.builtin.copy:
                mode: 0644
                src: pca-gophish-composition.service
                dest: /etc/systemd/system/pca-gophish-composition.service
            - name: Reload systemd daemon
              ansible.builtin.systemd:
                daemon_reload: true
            - name: >
                Enable pca-gophish-composition systemd service to start
                on boot
              ansible.builtin.systemd:
                name: pca-gophish-composition.service
                enabled: true
          when:
            - ansible_service_mgr == "systemd"
    - name: Create GoPhish desktop shortcut for VNC user
      block:
        - name: Create VNC user Desktop directory
          ansible.builtin.file:
            path: /home/{{ vnc_username }}/Desktop
            state: directory
            mode: 0755
            owner: "{{ vnc_username }}"
            group: "{{ vnc_username }}"
        - name: Create GoPhish desktop shortcut for VNC user
          ansible.builtin.copy:
            src: gophish-shortcut.desktop
            dest: /home/{{ vnc_username }}/Desktop/gophish-shortcut.desktop
            mode: 0755
            owner: "{{ vnc_username }}"
            group: "{{ vnc_username }}"
  vars:
    pca_gophish_composition_path: /var/pca/pca-gophish-composition
    vnc_username: "{{ lookup('aws_ssm', '/vnc/username') }}"
