---
- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

# The AWS playbook must run before this one, since this playbook uses
# a user group created in the AWS playbook.
- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

- name: Import PCA Gophish composition playbook
  ansible.builtin.import_playbook: pca_gophish.yml

- name: Import extras playbook
  ansible.builtin.import_playbook: extras.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml
