---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop

# AWS instance types expose EBS volumes as NVMe block devices, so install nvme
- hosts: aws
  name: Install nvme
  become: yes
  become_method: sudo
  roles:
    - nvme

- hosts: all
  name: Install VNC server
  become: yes
  become_method: sudo
  roles:
    - vnc_server

- hosts: all
  name: Install PCA GoPhish Docker composition
  become: yes
  become_method: sudo
  roles:
    - pca_gophish_composition

- hosts: all
  name: Change GoPhish published port from 3380 to 80
  become: yes
  become_method: sudo
  tasks:
    - name: Change GoPhish published port from 3380 to 80
      lineinfile:
        path: /var/pca/pca-gophish-composition/docker-compose.yml
        regexp: "published: 3380$"
        line: "        published: 80"
        state: present

- hosts: all
  name: Add VNC user to docker group
  become: yes
  become_method: sudo
  tasks:
    - name: Add VNC user to docker group
      user:
        name: "{{ lookup('aws_ssm', '/vnc/username') }}"
        groups: docker
        append: yes

- hosts: all
  name: Install Chromium web browser
  become: yes
  become_method: sudo
  tasks:
    - name: Install Chromium web browser
      package:
        name: chromium

- hosts: all
  name: Start up GoPhish Docker composition
  become: yes
  become_method: sudo
  tasks:
    - name: Start up GoPhish Docker composition
      docker_compose:
        project_src: /var/pca/pca-gophish-composition

- hosts: all
  name: Wait for GoPhish admin server to start up
  become: yes
  become_method: sudo
  tasks:
    - name: Wait for GoPhish admin port to be open
      wait_for:
        port: 3333

- hosts: all
  name: Get GoPhish API key
  become: yes
  become_method: sudo
  tasks:
    - name: Get GoPhish API key
      command: /usr/local/bin/docker-compose exec -T gophish get-api-key
      args:
        chdir: /var/pca/pca-gophish-composition
      register: gophish_api_key
      changed_when: false

- hosts: all
  name: Execute gophish-init
  become: yes
  become_method: sudo
  tasks:
    - name: Execute gophish-init
      command: /usr/local/bin/gophish-init {{ gophish_api_key.stdout }}
      changed_when: false
