---
- name: Import base image playbook
  import_playbook: base.yml

- name: Import VNC playbook
  import_playbook: vnc.yml

- name: Import PCA GoPhish composition playbook
  import_playbook: pca_gophish.yml

- name: Import extras playbook
  import_playbook: extras.yml

- name: Import cloud-init playbook
  import_playbook: cloud_init.yml

- name: Import AWS playbook
  import_playbook: aws.yml
