---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop

# AWS instance types expose EBS volumes as NVMe block devices, so install nvme
- hosts: aws
  name: Install nvme
  become: yes
  become_method: sudo
  roles:
    - nvme

- hosts: all
  name: Install VNC server
  become: yes
  become_method: sudo
  roles:
    - vnc_server

- hosts: all
  name: Install Chromium web browser
  become: yes
  become_method: sudo
  tasks:
    - name: Install Chromium web browser
      package:
        name: chromium

- hosts: all
  name: Install PCA GoPhish Docker composition
  become: yes
  become_method: sudo
  roles:
    - pca_gophish_composition

- hosts: all
  name: Create mount point for GoPhish persistent data volume
  become: yes
  become_method: sudo
  tasks:
    - name: Create mount point for GoPhish persistent data volume
      file:
        path: /var/pca/pca-gophish-composition/data
        state: directory

- hosts: all
  name: Change GoPhish published port from 3380 to 80
  become: yes
  become_method: sudo
  tasks:
    - name: Change GoPhish published port from 3380 to 80
      lineinfile:
        path: /var/pca/pca-gophish-composition/docker-compose.yml
        regexp: "published: 3380$"
        line: "        published: 80"
        state: present

- hosts: all
  name: Copy docker-compose.production.yml to pca-gophish-composition dir
  become: yes
  become_method: sudo
  tasks:
    - name: Copy docker-compose.production.yml to pca-gophish-composition dir
      copy:
        src: docker-compose.production.yml
        dest: /var/pca/pca-gophish-composition/docker-compose.production.yml

- hosts: all
  name: Install systemd service file for pca-gophish-composition
  become: yes
  become_method: sudo
  tasks:
    - name: Install systemd service file for pca-gophish-composition
      copy:
        src: pca-gophish-composition.service
        dest: /etc/systemd/system/pca-gophish-composition.service

- hosts: all
  name: Systemd daemon-reload
  become: yes
  become_method: sudo
  tasks:
    - name: Systemd daemon-reload
      systemd:
        daemon_reload: true
      when:
        - ansible_service_mgr == "systemd"

- hosts: all
  name: Systemd daemon-reload
  become: yes
  become_method: sudo
  tasks:
    - name: Enable pca-gophish-composition systemd service to start on boot
      systemd:
        name: pca-gophish-composition.service
        enabled: true
      when:
        - ansible_service_mgr == "systemd"

- hosts: all
  name: Add VNC user to docker group
  become: yes
  become_method: sudo
  tasks:
    - name: Add VNC user to docker group
      user:
        name: "{{ lookup('aws_ssm', '/vnc/username') }}"
        groups: docker
        append: yes
