- src: https://github.com/cisagov/ansible-role-banner
  name: banner
- src: https://github.com/cisagov/ansible-role-htop
  name: htop
- src: https://github.com/cisagov/ansible-role-nvme
  name: nvme
- src: https://github.com/cisagov/ansible-role-pca-gophish-composition
  name: pca-gophish-composition
- src: https://github.com/cisagov/ansible-role-persist-journald
  name: persist-journald
- src: https://github.com/cisagov/ansible-role-upgrade
  name: upgrade
