---
- name: Install Xfce
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install Xfce
      ansible.builtin.include_role:
        name: xfce_cool
      vars:
        # The users for whom a symlink to the COOL file share should
        # be created
        xfce_cool_usernames:
          - "{{ lookup('aws_ssm', '/vnc/username') }}"
